grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  env:
    GF_SERVER_ROOT_URL: http://20.246.186.164/grafana/
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

prometheus:
  prometheusSpec:
    externalUrl: http://20.246.186.164/prometheus
    routePrefix: /
