apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://username:password@cluster.mongodb.net/dbname?appName=YourApp
  JWT_SECRET: your-super-secret-jwt-key-change-this-in-prod
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_USER: your-email@gmail.com
  EMAIL_PASSWORD: your-app-password
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: AdminPassword123
  AZURE_OPENAI_ENDPOINT: https://your-resource.cognitiveservices.azure.com
  AZURE_OPENAI_API_KEY: your-api-key-here
  AZURE_OPENAI_DEPLOYMENT: gpt-4o-mini
  AZURE_OPENAI_API_VERSION: "2025-01-01-preview"
