apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "win_k8s.fullname" . }}
  labels:
    {{- include "win_k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "win_k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "win_k8s.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - name: backend
              containerPort: 5000
              protocol: TCP
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - name: frontend
              containerPort: 3000
              protocol: TCP
